/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package bitwarden

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/bitwarden/sdk-go"
	"github.com/go-chi/chi/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// This is a valid test token that has been generated and then revoked. The important
// bit is that it is in valid format. If ever this needs to be changed, it has to be
// regenerated by a valid bitwarden secret manager machine account.
const testToken = "0.0f0a8a7e-d737-498d-be6a-b1930064c31c.Rjqj7Vt7ZcDADtpbuzgx0hqbNJFPho:RZbls0Ka2gwIVKaLvSG3eA=="

// TODO: I need to figure out what the command requires as a response. It seems like it doesn't like
// whatever I throw at it.
func XTestWardenWithToken(t *testing.T) {
	// this is the bitwarden server mock
	success := sdk.APIKeyLoginResponse{
		Authenticated: true,
	}
	marshal, _ := json.Marshal(success)
	message := json.RawMessage(marshal)
	wrapper := struct {
		Success      bool             `json:"success"`
		ErrorMessage *string          `json:"errorMessage"`
		Data         *json.RawMessage `json:"data"`
	}{
		Success:      true,
		ErrorMessage: nil,
		Data:         &message,
	}

	bitwardenServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		wr, _ := json.Marshal(wrapper)
		w.Write(wr)
		w.WriteHeader(http.StatusAccepted)
	}))
	defer bitwardenServer.Close()

	// this is our warden test mock
	r := chi.NewRouter()
	r.Use(Warden)
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("test"))
		w.WriteHeader(http.StatusOK)
	})
	server := httptest.NewServer(r)
	defer server.Close()

	url := server.URL + "/"
	client := server.Client()
	req, err := http.NewRequest(http.MethodGet, url, bytes.NewBuffer([]byte(`{}`)))
	require.NoError(t, err)
	req.Header.Set(WardenHeaderAccessToken, testToken)
	req.Header.Set(WardenHeaderAPIURL, bitwardenServer.URL)
	req.Header.Set(WardenHeaderIdentityURL, bitwardenServer.URL)
	resp, err := client.Do(req)
	require.NoError(t, err)
	defer resp.Body.Close()
	content, err := io.ReadAll(resp.Body)
	require.NoError(t, err)
	fmt.Println(string(content))

	assert.Equal(t, http.StatusOK, resp.StatusCode)
}
