{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bitwarden-sdk-server.serviceAccountName" . }}
  namespace: {{ template "bitwarden-sdk-server.namespace" . }}
  labels:
    {{- include "bitwarden-sdk-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
